# Generated by Django 5.2.5 on 2025-08-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='phone',
            field=models.CharField(blank=True, null=True),
        ),
    ]
