services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d incidents"]
      interval: 5s
      retries: 5
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    environment:
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - ./.env
    volumes:
      - .:/app

  worker:
    build: .
    command: celery -A safetify worker --loglevel=INFO
    depends_on:
      - web
      - redis
