# Generated by Django 5.2.5 on 2025-08-15 02:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('private_id', models.CharField(editable=False, max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('last_name', models.CharField(max_length=255)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('is_superuser', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['id'], name='accounts_us_id_b41dd0_idx'), models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'), models.Index(fields=['-created_at'], name='accounts_us_created_d650d4_idx')],
            },
        ),
    ]
