# Generated by Django 5.2.5 on 2025-08-15 02:13

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('technicians', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('severity', models.PositiveSmallIntegerField(default=1)),
                ('risk_score', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('assigned', 'Assigned'), ('resolved', 'Resolved')], default='queued', max_length=16)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distance_meters', models.FloatField()),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='technicians.technician')),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='incidents.incident')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
